CREATE DATABASE JSANCHEZLAUDEX
USE JSANCHEZLAUDEX
GO

CREATE TABLE TAREA
(
IDTAREA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TITULO VARCHAR(250) NOT NULL,
DESCRIPCION VARCHAR(250) NOT NULL,
FECHAVENCIMIENTO DATE NOT NULL,
ESTADO SMALLINT NOT NULL
)
GO

CREATE PROCEDURE TareaAdd --'Pendiente 2','Realizar los pendientes 2','23/01/2024'
@TITULO VARCHAR(250),
@DESCRIPCION VARCHAR(250),
@FECHAVENCIMIENTO VARCHAR(250)
AS
INSERT INTO TAREA (TITULO,DESCRIPCION,FECHAVENCIMIENTO,ESTADO)
VALUES (@TITULO,@DESCRIPCION,CONVERT(date,@FECHAVENCIMIENTO,105),1)
GO

CREATE PROCEDURE TareaUpdate
@IDTAREA INT,
@TITULO VARCHAR(250),
@DESCRIPCION VARCHAR(250),
@FECHAVENCIMIENTO VARCHAR(250),
@ESTADO SMALLINT
AS
UPDATE TAREA SET 
TITULO=@TITULO,DESCRIPCION=@DESCRIPCION,FECHAVENCIMIENTO=@FECHAVENCIMIENTO,ESTADO=@ESTADO
WHERE IDTAREA=@IDTAREA
GO

CREATE PROCEDURE TareaDelete
@IDTAREA INT
AS
UPDATE TAREA SET ESTADO=0 WHERE IDTAREA=@IDTAREA
GO

CREATE PROCEDURE TareaGetAll --0
@ESTADO SMALLINT
AS
BEGIN
UPDATE TAREA SET ESTADO = 0 WHERE FECHAVENCIMIENTO < SYSDATETIME()

	IF(@ESTADO = 1)
		SELECT IDTAREA,TITULO,DESCRIPCION,FECHAVENCIMIENTO,ESTADO FROM TAREA
		WHERE ESTADO = @ESTADO
	ELSE
		SELECT IDTAREA,TITULO,DESCRIPCION,FECHAVENCIMIENTO,ESTADO FROM TAREA
		WHERE ESTADO = 0
END
GO

CREATE PROCEDURE TareaGetById
@IDTAREA INT
AS
SELECT IDTAREA,TITULO,DESCRIPCION,FECHAVENCIMIENTO,ESTADO FROM TAREA
WHERE IDTAREA=@IDTAREA
GO